Screen:
    name: "LOGIN"
    MDBoxLayout:

        MDNavigationRail:

            MDNavigationRailItem:
                text: "Python"
                icon: "language-python"

            MDNavigationRailItem:
                text: "JavaScript"
                icon: "language-javascript"

            MDNavigationRailItem:
                text: "CPP"
                icon: "language-cpp"

            MDNavigationRailItem:
                text: "Git"
                icon: "git"

        MDScreen: